### ISSUE TITLE
Weird query lifecycle transitions

### ISSUE THREAD

**Issue by olistic** [jaydenseric/graphql-react#38] opened 2019-05-30 17:09 UTC
Hey there! I discovered your library yesterday and decided to give it a try because I think its caching mechanism is superior to what [graphql-hooks](https://github.com/nearform/graphql-hooks) (what I'm currently using) offers.

## What I'm doing

To make migration easier, I'm creating the following hook:

```js
import { useGraphQL } from 'graphql-react';

const fetchOptionsOverride = options => {
  options.url = '/api/graphql';
};

const useQuery = (query, { variables } = {}) => {
  const {
    loading,
    cacheValue: { data, fetchError, httpError, parseError, graphQLErrors } = {},
  } = useGraphQL({
    fetchOptionsOverride,
    operation: {
      variables,
      query,
    },
  });

  const error = fetchError || httpError || parseError || graphQLErrors;

  console.log({ loading, error, data }); // <- Remember this call to console.log.

  return {
    loading,
    error,
    data,
  };
};

export default useQuery;
```

## What I expect

Later, in my component I expect to be able to use `useQuery` like this:

```js
const postQuery = /* GraphQL */ `...`;

const Post = ({ postId }) => {
  const { loading, error, data } = useQuery(postQuery, {
    variables: {
      postId,
    },
  });

  if (loading) {
    return 'Loading...';
  }

  if (error) {
    return 'Something went wrong.';
  }

  return (
    <article>
      <h1>{data.post.title}</h1>
      <p>{data.post.content}</p>
    </article>
  );
};
```

## What actually happens

Blows up when trying to access `data.post.title`. I traced that down to the different values `loading`, `error` and `data` have during the query lifecycle:

1. `{ loading: false, error: undefined, data: undefined }`

All three values are falsy at the beginning, thus provoking the issue I just mentioned with my component's code.

2. `{ loading: true, error: undefined, data: undefined }`

`loading` is set to `true` when `load()` is called inside `useGraphQL`.

3. `{ loading: false, error: undefined, data: undefined }`

When that finishes, `loading` returns to `false`, but neither `error` nor `data` are set (problematic, if you ask me).

4. `{ loading: false, error: undefined, data: {…} }`

Finally, `data` is populated with the result of the GraphQL query.

I would expect this sequence to be like this instead:

1. `{ loading: true, error: undefined, data: undefined }`
2. `{ loading: false, error: undefined, data: {…} }`

**Am I doing something wrong in my `useQuery` hook? Is this the expected behavior?**

**Comment by jaydenseric** [comment] 2019-05-31 03:07
I'm not sure why at first you're getting `loading: false`, since in the tests that does not happen:

https://github.com/jaydenseric/graphql-react/blob/1b1234de5de46b7a0029903a1446dcc061f37d09/src/test/useGraphQL.mjs#L75

**Comment by olistic** [comment] 2019-06-02 22:10
Yeah, weird. Let me try to reproduce the issue in a codesandbox. If I'm doing something wrong I'll probably find out then. I'll keep you posted.

**Comment by olistic** [comment] 2019-06-02 23:25
@jaydenseric I was able to reproduce it in this [codesandbox](https://codesandbox.io/s/romantic-cache-muzsf?fontsize=14).

**Comment by jaydenseric** [comment] 2019-06-05 07:04
Bear with me, but I think this may be working as intended.

It's been a while since I dove ***deep*** into React hooks, exploring all the gotchas (`console.log` debugging hooks is confusing), but here are my rusty thoughts…

The first log of `loading: false` is correct; because that state only updates once it actually starts loading, which is not until after it mounts. The first console.log can be from a render that happened before the `useEffect` triggers loading. Note that in the situation where the exact same query is already loading in the client (triggered by something somewhere else) at the time the component mounts, the first log may be `loading: true`.

Now my memory may be hazy/wrong, but when multiple `useState` values are updated internally there can be multiple re-renders, but you don't actually see each re-render happen in the real DOM if they happen quickly.

You do need to make sure you nest any JSX using `cacheValue.data` in a conditional that checks `data` actually exists first.

**Comment by jaydenseric** [comment] 2019-12-05 00:36
Closing because I'm pretty sure everything is working as intended; the general rule is to account for `cacheValue` sometimes not being defined, as documented in all the `useGraphQL` examples:

```jsx
const { loading, cacheValue = {} } = useGraphQL({
  // …
})
```

https://github.com/jaydenseric/graphql-react/tree/v9.1.0#examples-8

I always do `cacheValue = {}`, and haven't had any problems in all my apps.

It's potentially useful to be able to tell when rendering if there is no cache for a particular query, so it's probably good to leave the API the way it is and not default `cacheValue` to an empty object.

**Comment by Grsmto** [comment] 2020-01-27 19:25
I'm having the same issue and I did a reproductible example with the doc snippet fetching a Pokemon: https://codesandbox.io/s/gracious-leakey-hisdk

As described by @olistic there is a state that imo should not happen:

1. loading starts: `{ loading: true, data: undefined }`

2 loading is finished **but** `data` is still `undefined`??   `{ loading: false, data: undefined }`
This state does not make sense because it then trigger the `if` condition display `Error` in the CodeSandbox.

3. One tick later, finally the `data` is there: `{ loading: false, data: {…} }`

As you can see in that CodeSandbox I don't think there is any external hook hijacking the render loop in the middle that could cause that. So it seems to come from `graphql-react`.
In my app this is actually causing an issue since I'm displaying an error message with a **transition animation** so even if the wrong state is really short, it stills trigger the in/out animation creating a flash of the error state.

**Comment by jaydenseric** [comment] 2020-01-27 21:13
@Grsmto are you using `console.log` to debug the hook return value? A quick guess is that internally two `useState` values are being set, one immediately after the other, which in React can result in two very fast "renders", but only one change to the DOM.

I plan to look into how these lifecycle gotchas can be improved when I start work on the next version; I've been working hard on other projects lately (several new testing related packages, and [`graphql-upload` v10](https://github.com/jaydenseric/graphql-upload/releases/tag/v10.0.0)), and now I've got full time contract work to contend with.

**Comment by Grsmto** [comment] 2020-01-28 14:53
Thanks for your quick reply. 

>internally two useState values are being set, one immediately after the other, which in React can result in two very fast "renders"

Actually as you can see in this codesandbox example, that's not the case: https://codesandbox.io/s/green-architecture-023dc
Doing 2 following `setState` still will trigger 1 single render with both  `setState` applied at the same time (not one after the other).

Anyway I will try to have a look at the source code of the `useGraphQL` see if I find something. Good luck with your new contract!

**Comment by jaydenseric** [comment] 2020-03-25 09:24
This should be improved in [v10.0.0](https://github.com/jaydenseric/graphql-react/releases/tag/v10.0.0) 🚀

**Closed by jaydenseric** 2020-03-25 09:24 UTC
